package id.shakala.bakery;

import android.Manifest;
import android.app.AlertDialog;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothSocket;
import android.content.ContentValues;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends AppCompatActivity {
    static final int BROWN=Color.rgb(85,58,46), ORANGE=Color.rgb(184,91,53), CREAM=Color.rgb(248,245,240), GREEN=Color.rgb(76,139,101);
    Db db; SharedPreferences prefs; LinearLayout content; final Map<Integer,Integer> cart=new LinkedHashMap<>(); double cash=0; String payment="Tunai"; String printerName="RPP02";
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView text(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(BROWN);v.setPadding(dp(10),dp(8),dp(10),dp(8));return v;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(BROWN);return b;} Button primary(String s){Button b=button(s);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(ORANGE);return b;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(12),dp(16),dp(16));return l;} ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.addView(v);return s;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);prefs=getSharedPreferences("shakala",0);seed();showLogin();}
    void seed(){if(db.countProducts()>0)return;String[][] p={{"Donat Gula","Donat","5000","24"},{"Donat Cokelat","Donat","7000","18"},{"Donat Tiramisu","Donat","8000","12"},{"Bomboloni Cokelat","Bomboloni","10000","15"},{"Bomboloni Vanilla","Bomboloni","10000","11"},{"Roti Sosis","Roti","9000","9"},{"Kopi Susu","Minuman","12000","20"},{"Teh Manis","Minuman","5000","30"}};for(String[] x:p)db.addProduct(x[0],x[1],Double.parseDouble(x[2]),Integer.parseInt(x[3]));}
    void showLogin(){LinearLayout l=col();l.setGravity(Gravity.CENTER_HORIZONTAL);Space sp=new Space(this);l.addView(sp,new LinearLayout.LayoutParams(1,dp(80)));TextView logo=text("🌾  Shakala\n     BAKERY",30);logo.setGravity(Gravity.CENTER);logo.setTextColor(BROWN);l.addView(logo);TextView title=text("Selamat datang",26);title.setGravity(Gravity.CENTER);l.addView(title);TextView hint=text("Masuk untuk mulai melayani pelanggan.",14);hint.setGravity(Gravity.CENTER);l.addView(hint);EditText pin=new EditText(this);pin.setHint("Masukkan PIN");pin.setInputType(2|16);pin.setGravity(Gravity.CENTER);l.addView(pin,new LinearLayout.LayoutParams(-1,dp(55)));Button masuk=primary("MASUK KE KASIR");l.addView(masuk,new LinearLayout.LayoutParams(-1,dp(55)));TextView error=text("",13);error.setTextColor(Color.RED);error.setGravity(Gravity.CENTER);l.addView(error);l.addView(text("Shakala Bakery · Kediri",12));setContentView(l);pin.requestFocus();getWindow().setSoftInputMode(4);masuk.setOnClickListener(v->{String saved=prefs.getString("pin","170117");if(pin.getText().toString().equals(saved))showMain();else error.setText("PIN belum benar");});}
    void showMain(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM);LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(6),dp(5),dp(6),dp(5));String[] tabs={"Kasir","Dashboard","Produk","Laporan","Pengaturan"};for(String t:tabs){Button b=button(t);b.setTextSize(11);bar.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));b.setOnClickListener(v->{if(t.equals("Kasir"))pos();else if(t.equals("Dashboard"))dashboard();else if(t.equals("Produk"))products();else if(t.equals("Laporan"))reports();else settings();});}root.addView(bar);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);pos();}
    void clear(){content.removeAllViews();}
    void pos(){clear();TextView h=text("Selamat pagi, Kasir!",25);h.setTypeface(null,1);content.addView(h);TextView sub=text("Penjualan hari ini: "+money(db.dayTotal())+"  ·  "+db.dayCount()+" transaksi",13);content.addView(sub);LinearLayout body=col();for(final Db.Product p:db.products()){Button b=button(p.name+"\n"+money(p.price)+"  ·  stok "+p.stock);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);body.addView(b,new LinearLayout.LayoutParams(-1,dp(70)));b.setOnClickListener(v->{if(p.stock<=0){toast("Stok habis");return;}cart.put(p.id,cart.getOrDefault(p.id,0)+1);renderCart();});}content.addView(scroll(body),new LinearLayout.LayoutParams(-1,0,1));renderCart();}
    void renderCart(){if(content==null)return;LinearLayout bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.VERTICAL);bottom.setPadding(dp(12),dp(4),dp(12),dp(8));StringBuilder s=new StringBuilder("Pesanan: ");double total=0;for(Map.Entry<Integer,Integer> e:cart.entrySet()){Db.Product p=db.product(e.getKey());s.append(p.name).append(" x").append(e.getValue()).append("   ");total+=p.price*e.getValue();}TextView sum=text(s+"\nTOTAL "+money(total),15);sum.setTypeface(null,1);bottom.addView(sum);LinearLayout pay=new LinearLayout(this);for(String x:new String[]{"Tunai","QRIS","Transfer"}){Button b=button(x);pay.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));b.setOnClickListener(v->{payment=x;});}bottom.addView(pay);EditText uang=new EditText(this);uang.setHint("Uang diterima (tunai)");uang.setInputType(2|8192);bottom.addView(uang,new LinearLayout.LayoutParams(-1,dp(52)));Button bayar=primary("BAYAR & BUAT INVOICE");bottom.addView(bayar,new LinearLayout.LayoutParams(-1,dp(52)));bayar.setEnabled(!cart.isEmpty());uang.setOnFocusChangeListener((v,f)->{});uang.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){try{cash=Double.parseDouble(s.toString());}catch(Exception e){cash=0;}bayar.setEnabled(!cart.isEmpty()&&(!payment.equals("Tunai")||cash>=total));}public void afterTextChanged(android.text.Editable e){}});bayar.setOnClickListener(v->{if(payment.equals("Tunai")&&cash<total){toast("Uang diterima kurang");return;}checkout(total);});content.addView(bottom);}
    void checkout(double total){String invoice=db.saveTransaction(total,payment);for(Map.Entry<Integer,Integer> e:cart.entrySet())db.reduceStock(e.getKey(),e.getValue());String detail="Invoice "+invoice+"\nTotal: "+money(total)+"\nPembayaran: "+payment+(payment.equals("Tunai")?"\nKembalian: "+money(cash-total):"");new AlertDialog.Builder(this).setTitle("Transaksi Berhasil").setMessage(detail).setNegativeButton("Tutup",null).setPositiveButton("Cetak Struk",(d,w)->print(invoice,total)).show();cart.clear();cash=0;pos();}
    void print(String invoice,double total){if(Build.VERSION.SDK_INT>=31&&!has(Manifest.permission.BLUETOOTH_CONNECT)){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},90);toast("Izinkan Nearby devices, lalu tekan cetak lagi");return;}new Thread(()->{try{BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();BluetoothDevice target=null;for(BluetoothDevice d:a.getBondedDevices())if(d.getName()!=null&&d.getName().toLowerCase().contains(printerName.toLowerCase())){target=d;break;}if(target==null){runOnUiThread(()->toast("Printer "+printerName+" belum dipairing"));return;}BluetoothSocket s=target.createRfcommSocketToServiceRecord(UUID.fromString("00001101-0000-1000-8000-00805F9B34FB"));s.connect();OutputStream o=s.getOutputStream();String r="SHAKALA BAKERY\nJln Ngasinan No.10 Rejomulyo Kediri\n"+invoice+"\nTOTAL "+money(total)+"\nTerima kasih\n\n\n";o.write(new byte[]{27,64});o.write(r.getBytes(StandardCharsets.UTF_8));o.write(new byte[]{29,86,0});o.flush();s.close();runOnUiThread(()->toast("Struk terkirim ke "+printerName));}catch(Exception e){runOnUiThread(()->toast("Gagal cetak: "+e.getMessage()));}}).start();}
    boolean has(String p){return Build.VERSION.SDK_INT<23||checkSelfPermission(p)==PackageManager.PERMISSION_GRANTED;}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    void dashboard(){clear();LinearLayout l=col();l.addView(text("Dashboard",26));l.addView(text("Pendapatan hari ini\n"+money(db.dayTotal())+"\n\nTotal transaksi\n"+db.dayCount(),18));l.addView(text("Produk terlaris\n"+db.bestSeller(),16));content.addView(scroll(l));}
    void products(){clear();LinearLayout l=col();l.addView(text("Tambah Produk",25));EditText name=input("Nama produk");EditText cat=input("Kategori");EditText price=input("Harga jual");EditText stock=input("Stok awal");price.setInputType(2);stock.setInputType(2);l.addView(name);l.addView(cat);l.addView(price);l.addView(stock);Button add=primary("SIMPAN PRODUK");l.addView(add);TextView result=text("",13);l.addView(result);add.setOnClickListener(v->{try{db.addProduct(name.getText().toString(),cat.getText().toString(),Double.parseDouble(price.getText().toString()),Integer.parseInt(stock.getText().toString()));result.setText("Produk tersimpan");name.setText("");price.setText("");stock.setText("");}catch(Exception e){result.setText("Isi nama, harga, dan stok dengan benar");}});l.addView(text("Daftar produk",20));for(Db.Product p:db.products())l.addView(text(p.name+"  ·  "+money(p.price)+"  · stok "+p.stock,14));content.addView(scroll(l));}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setPadding(dp(8),dp(5),dp(8),dp(5));return e;}
    void reports(){clear();LinearLayout l=col();l.addView(text("Laporan Keuangan",25));l.addView(text("Total pendapatan: "+money(db.allTotal())+"\nTotal transaksi: "+db.allCount(),17));for(String x:db.transactions())l.addView(text(x,13));Button export=button("Ekspor / Bagikan Laporan");l.addView(export);export.setOnClickListener(v->toast("Laporan siap: "+db.allCount()+" transaksi"));content.addView(scroll(l));}
    void settings(){clear();LinearLayout l=col();l.addView(text("Pengaturan",25));EditText pin=input("PIN baru");pin.setInputType(2|16);l.addView(pin);Button save=primary("SIMPAN PIN");l.addView(save);save.setOnClickListener(v->{if(pin.length()<4){toast("PIN minimal 4 angka");return;}prefs.edit().putString("pin",pin.getText().toString()).apply();toast("PIN berhasil diubah");});EditText printer=input("Nama printer, contoh RPP02");printer.setText(printerName);l.addView(printer);Button connect=button("IZINKAN & TES PRINTER");l.addView(connect);connect.setOnClickListener(v->{printerName=printer.getText().toString().trim();if(Build.VERSION.SDK_INT>=31&&!has(Manifest.permission.BLUETOOTH_CONNECT)){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},90);}else toast("Izin sudah aktif. Tekan Cetak Struk setelah transaksi.");});l.addView(text("Android native menggunakan Bluetooth Classic RFCOMM/SPP untuk printer RPP02 yang sudah dipairing.",13));content.addView(scroll(l));}
    @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==90)toast(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED?"Izin Bluetooth aktif":"Izin Bluetooth ditolak");}
    String money(double n){return NumberFormat.getCurrencyInstance(new Locale("id","ID")).format(n).replace(",00","");}

    static class Db extends android.database.sqlite.SQLiteOpenHelper { Product[] cache=new Product[0]; Db(Context c){super(c,"shakala.db",null,1);}public void onCreate(android.database.sqlite.SQLiteDatabase d){d.execSQL("CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,cat TEXT,price REAL,stock INTEGER)");d.execSQL("CREATE TABLE tx(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice TEXT,total REAL,payment TEXT,created INTEGER)");}public void onUpgrade(android.database.sqlite.SQLiteDatabase d,int a,int b){}int countProducts(){return getReadableDatabase().rawQuery("SELECT id FROM products",null).getCount();}void addProduct(String n,String c,double p,int s){ContentValues v=new ContentValues();v.put("name",n);v.put("cat",c);v.put("price",p);v.put("stock",s);getWritableDatabase().insert("products",null,v);}List<Product> products(){ArrayList<Product> a=new ArrayList<>();android.database.Cursor c=getReadableDatabase().rawQuery("SELECT id,name,cat,price,stock FROM products ORDER BY id",null);while(c.moveToNext())a.add(new Product(c.getInt(0),c.getString(1),c.getString(2),c.getDouble(3),c.getInt(4)));c.close();return a;}Product product(int id){for(Product p:products())if(p.id==id)return p;return null;}void reduceStock(int id,int q){getWritableDatabase().execSQL("UPDATE products SET stock=MAX(0,stock-?) WHERE id=?",new Object[]{q,id});}String saveTransaction(double t,String p){String i="INV-"+(System.currentTimeMillis()%100000000);ContentValues v=new ContentValues();v.put("invoice",i);v.put("total",t);v.put("payment",p);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("tx",null,v);return i;}int dayCount(){return scalar("SELECT COUNT(*) FROM tx WHERE date(created/1000,'unixepoch','localtime')=date('now','localtime')");}double dayTotal(){return total("WHERE date(created/1000,'unixepoch','localtime')=date('now','localtime')");}int allCount(){return scalar("SELECT COUNT(*) FROM tx");}double allTotal(){return total("");}String bestSeller(){return products().isEmpty()?"Belum ada data":products().get(0).name;}int scalar(String q){android.database.Cursor c=getReadableDatabase().rawQuery(q,null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}double total(String where){android.database.Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(total),0) FROM tx "+where,null);double n=c.moveToFirst()?c.getDouble(0):0;c.close();return n;}ArrayList<String> transactions(){ArrayList<String>a=new ArrayList<>();android.database.Cursor c=getReadableDatabase().rawQuery("SELECT invoice,total,payment FROM tx ORDER BY id DESC",null);while(c.moveToNext())a.add(c.getString(0)+" · "+c.getString(2)+" · "+c.getDouble(1));c.close();return a;}static class Product{int id,stock;String name,cat;double price;Product(int i,String n,String c,double p,int s){id=i;name=n;cat=c;price=p;stock=s;}}
    }
}
